//! Canonical list of Axum routes implemented on `feature/axum-migration`.
//! Kept in sync with `migration/axum-route-inventory.golden` (Task 18 parity gate; Task 19 policy routes).

/// HTTP method + Express-style path pattern (`{id}` placeholders).
pub const IMPLEMENTED_ROUTES: &[(&str, &str)] = &[
    ("GET", "/health"),
    ("GET", "/api/platform/health"),
    ("GET", "/api/platform/runtime"),
    ("GET", "/api/platform/env-health"),
    ("GET", "/api/platform/config"),
    ("POST", "/api/platform/config/propose-update"),
    ("GET", "/api/platform/tenants"),
    ("POST", "/api/platform/tenants"),
    ("GET", "/api/platform/tenants/{id}"),
    ("POST", "/api/platform/tenants/{id}/propose-update"),
    ("GET", "/api/platform/memberships"),
    ("POST", "/api/platform/memberships"),
    ("GET", "/api/platform/memberships/{user_id}/{tenant_id}"),
    ("PATCH", "/api/platform/memberships/{user_id}/{tenant_id}"),
    ("DELETE", "/api/platform/memberships/{user_id}/{tenant_id}"),
    ("GET", "/api/platform/grants"),
    ("POST", "/api/platform/grants"),
    ("DELETE", "/api/platform/grants/{id}"),
    ("GET", "/api/governance/proposals"),
    ("POST", "/api/governance/proposals"),
    ("GET", "/api/governance/proposals/pending-count"),
    ("GET", "/api/governance/proposals/{id}"),
    ("POST", "/api/governance/proposals/{id}/approve"),
    ("POST", "/api/governance/proposals/{id}/reject"),
    ("GET", "/api/geo/grounding/status"),
    ("POST", "/api/geo/grounding/invoke"),
    ("POST", "/api/auth/login"),
    ("POST", "/api/auth/register"),
    ("GET", "/api/auth/me"),
    ("POST", "/api/auth/refresh"),
    ("POST", "/api/auth/logout"),
    ("POST", "/api/auth/logout-all"),
    ("GET", "/api/auth/events"),
    ("GET", "/api/auth/oauth/config"),
    ("GET", "/api/auth/email/status"),
    ("POST", "/api/auth/forgot-password"),
    ("POST", "/api/auth/reset-password"),
    ("GET", "/api/auth/verify-email"),
    ("GET", "/api/auth/apple"),
    ("GET", "/api/auth/apple/callback"),
    ("POST", "/api/auth/send-verification-email"),
    ("POST", "/api/auth/resend-verification"),
    ("POST", "/api/auth/forgot-username"),
    ("POST", "/api/auth/change-password"),
    ("GET", "/api/v1/account/profile-extra"),
    ("PUT", "/api/v1/account/profile-extra"),
    ("POST", "/api/auth/google/exchange"),
    ("POST", "/api/auth/github/exchange"),
    ("POST", "/api/auth/linkedin/exchange"),
    ("POST", "/api/auth/oauth-upsert"),
    ("POST", "/api/auth/apple/exchange"),
    ("GET", "/api/geo/locations"),
    ("POST", "/api/geo/locations"),
    ("GET", "/api/aoi"),
    ("POST", "/api/aoi"),
    ("DELETE", "/api/aoi/{id}"),
    ("GET", "/api/weather/latest"),
    ("POST", "/api/ai/analyze"),
    ("POST", "/api/ai/chat"),
    ("GET", "/api/user/api-tokens"),
    ("GET", "/api/user/api-tokens/session"),
    ("PUT", "/api/user/api-tokens/{provider}"),
    ("DELETE", "/api/user/api-tokens/{provider}"),
    ("GET", "/api/system/tokens"),
    ("GET", "/api/system/tokens/status"),
    ("PUT", "/api/system/tokens/{name}"),
    ("PATCH", "/api/system/tokens/{name}"),
    ("POST", "/api/system/tokens/{name}/test"),
    ("POST", "/api/system/tokens/migrate-from-vault"),
    ("POST", "/api/log/client"),
    ("GET", "/api/rbac/me"),
    ("GET", "/api/rbac/users"),
    ("POST", "/api/rbac/users"),
    ("PATCH", "/api/rbac/users/{id}"),
    ("DELETE", "/api/rbac/users/{id}"),
    ("POST", "/api/rbac/users/{id}/approve"),
    ("POST", "/api/rbac/users/{id}/suspend"),
    ("POST", "/api/rbac/users/{id}/reactivate"),
    ("GET", "/api/rbac/audit"),
    ("GET", "/api/rbac/invites"),
    ("POST", "/api/rbac/invites"),
    ("GET", "/api/rbac/invites/preview"),
    ("POST", "/api/rbac/invites/accept"),
    ("GET", "/api/rbac/permissions/matrix"),
    ("GET", "/api/rbac/policies"),
    ("POST", "/api/rbac/policies"),
    ("GET", "/api/rbac/policies/{id}"),
    ("PATCH", "/api/rbac/policies/{id}"),
    ("DELETE", "/api/rbac/policies/{id}"),
    ("POST", "/api/rbac/policies/{id}/activate"),
    ("GET", "/api/billing/plans"),
    ("GET", "/api/billing/me"),
    ("POST", "/api/billing/start-trial"),
    ("POST", "/api/billing/activate"),
    ("POST", "/api/billing/payment-intent"),
    ("POST", "/api/billing/create-checkout-session"),
    ("POST", "/api/billing/confirm-payment"),
    ("POST", "/api/billing/bank-transfer"),
    ("GET", "/api/billing/invoices"),
    ("POST", "/api/billing/webhook"),
    ("GET", "/api/config/claude"),
    ("GET", "/api/config/deepseek"),
    ("GET", "/api/config/gemini"),
    ("GET", "/api/config/graphhopper"),
    ("GET", "/api/config/mapbox"),
    ("GET", "/api/config/mapbox/public-token"),
    ("GET", "/api/config/openai"),
    ("GET", "/api/config/openrouteservice"),
    ("GET", "/api/config/openweathermap"),
    ("GET", "/api/config/sentinel"),
    ("GET", "/api/config/status"),
    ("GET", "/api/gateway/status"),
    ("GET", "/api/gateway/mapbox/public-token"),
    ("GET", "/api/gateway/mapbox/proxy"),
    ("GET", "/api/gateway/mapbox/geocoding"),
    ("GET", "/api/gateway/sentinel/credentials"),
    ("GET", "/api/mapbox-proxy"),
    ("GET", "/api/google-3d-tiles-proxy"),
    ("GET", "/api/google-3d-tiles/root.json"),
    ("GET", "/api/github/status"),
    ("GET", "/api/github/events"),
    ("GET", "/api/github/oauth/start"),
    ("GET", "/api/github/oauth/callback"),
    ("GET", "/api/github/repos"),
    ("GET", "/api/github/repos/{owner}/{repo}/issues"),
    ("GET", "/api/github/repos/{owner}/{repo}/pulls"),
    ("POST", "/api/github/repos/{owner}/{repo}/issues"),
    ("POST", "/api/gateway/openrouteservice/{*path}"),
    ("GET", "/api/gateway/graphhopper/{*path}"),
    ("GET", "/api/gateway/openweathermap/{*path}"),
    ("POST", "/api/github/disconnect"),
    ("POST", "/api/gateway/gemini/generate-content"),
    ("POST", "/api/gateway/openai/chat"),
    ("POST", "/api/gateway/claude/messages"),
    ("POST", "/api/gateway/deepseek/chat"),
    ("GET", "*"),
];

/// Sorted TSV lines (`METHOD\tPATH`) for golden-file comparison.
pub fn golden_lines() -> Vec<String> {
    let mut lines: Vec<String> = IMPLEMENTED_ROUTES
        .iter()
        .map(|(method, path)| format!("{method}\t{path}"))
        .collect();
    lines.sort();
    lines
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn routes_are_unique() {
        let mut seen = std::collections::BTreeSet::new();
        for (method, path) in IMPLEMENTED_ROUTES {
            let key = format!("{method} {path}");
            assert!(seen.insert(key), "duplicate route: {method} {path}");
        }
    }
}
