// Deploy backend to the Hostinger VPS running api.geosyntra.org.
//
// What it does:
//   1. Builds a tarball of backend/ (excludes node_modules, .git, .env*).
//   2. Generates a production .env from hostinger.secrets.env with VPS path overrides.
//   3. Uploads both over SSH (ssh2, password auth from hostinger.secrets.env).
//   4. Extracts, installs deps, restarts the systemd service, and verifies HTTPS.
//
// Usage:
//   npm run vps:deploy            full deploy (code + env + npm install + restart)
//   npm run vps:deploy -- --env   only refresh .env + restart (skip code/tarball)
//   npm run vps:deploy -- --no-install   skip npm install (faster when deps unchanged)
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const backendDir = path.join(root, 'backend');

const args = process.argv.slice(2);
const ENV_ONLY = args.includes('--env');
const SKIP_INSTALL = args.includes('--no-install');

function loadEnvFile(p) {
  const out = {};
  if (!fs.existsSync(p)) return out;
  for (const line of fs.readFileSync(p, 'utf8').split(/\r?\n/)) {
    if (/^\s*#/.test(line) || !line.trim()) continue;
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (!m) continue;
    let v = m[2];
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    out[m[1]] = v;
  }
  return out;
}

const secrets = loadEnvFile(path.join(root, 'hostinger.secrets.env'));
const HOST = process.env.VPS_HOST || secrets.VPS_HOST;
const PORT = Number(process.env.VPS_SSH_PORT || secrets.VPS_SSH_PORT || 22);
const USER = process.env.VPS_SSH_USER || secrets.VPS_SSH_USER || 'root';
const PASS = process.env.VPS_ROOT_PASS || secrets.VPS_ROOT_PASS;
const APP_DIR = process.env.VPS_APP_DIR || secrets.VPS_APP_DIR || '/opt/geosyntra-api';
const DATA_DIR = '/var/lib/geosyntra-api';
const SERVICE = 'geosyntra-api';
const API_BASE = secrets.VITE_API_BASE_URL || 'https://api.geosyntra.org';

if (!HOST || !PASS) {
  console.error('Missing VPS_HOST or VPS_ROOT_PASS in hostinger.secrets.env');
  process.exit(2);
}

// Keys that are infra/deploy-only and must never be written to the server .env
const INFRA_KEYS = new Set([
  'HOSTINGER_SERVER_IP', 'HOSTINGER_FTP_HOST', 'HOSTINGER_FTP_USER', 'HOSTINGER_FTP_PATH',
  'HOSTINGER_SSH_HOST', 'HOSTINGER_SSH_USER', 'HOSTINGER_SSH_PORT', 'HOSTINGER_SSH_PASS',
  'HOSTINGER_APP_DIR', 'HOSTINGER_PM2_NAME', 'VITE_API_BASE_URL',
  'VPS_HOST', 'VPS_SSH_PORT', 'VPS_SSH_USER', 'VPS_ROOT_PASS', 'VPS_APP_DIR',
]);

function buildServerEnv() {
  const lines = [
    '# Generated by scripts/vps-deploy.mjs — do not edit on the server (overwritten on deploy).',
    `# ${new Date().toISOString()}`,
    'GEOSYNTRA_ENV=production',
    'NODE_ENV=production',
    `AGRI_DATA_DIR=${DATA_DIR}`,
    `AGRI_USER_DB_PATH=${DATA_DIR}/geosyntra_platform.db`,
  ];
  const seen = new Set(['GEOSYNTRA_ENV', 'NODE_ENV', 'AGRI_DATA_DIR', 'AGRI_USER_DB_PATH']);
  for (const [k, v] of Object.entries(secrets)) {
    if (INFRA_KEYS.has(k) || seen.has(k) || !v) continue;
    lines.push(`${k}=${v}`);
    seen.add(k);
  }
  // Mirror a pk.* Mapbox token into MAPBOX_PUBLIC_TOKEN for the browser GL client.
  const mapbox = secrets.MAPBOX_TOKEN || secrets.MAPBOX || '';
  if (mapbox.startsWith('pk.') && !seen.has('MAPBOX_PUBLIC_TOKEN')) {
    lines.push(`MAPBOX_PUBLIC_TOKEN=${mapbox}`);
  }
  return lines.join('\n') + '\n';
}

function buildTarball() {
  const out = path.join(os.tmpdir(), 'geosyntra-backend-deploy.tgz');
  execFileSync('tar', [
    '--exclude=node_modules', '--exclude=.git', '--exclude=.env', '--exclude=.env.vps', '--exclude=.env.example',
    '-czf', out, '.',
  ], { cwd: backendDir, stdio: ['ignore', 'inherit', 'inherit'] });
  return out;
}

let ssh2;
try { ssh2 = await import('ssh2'); }
catch { console.error('ssh2 not installed. Run: npm install ssh2 --no-save'); process.exit(2); }
const { Client } = ssh2.default || ssh2;

function connect() {
  return new Promise((resolve, reject) => {
    const conn = new Client();
    conn.on('ready', () => resolve(conn)).on('error', reject)
      .connect({ host: HOST, port: PORT, username: USER, password: PASS, readyTimeout: 30000, keepaliveInterval: 10000 });
  });
}
function exec(conn, cmd) {
  return new Promise((resolve, reject) => {
    conn.exec(cmd, { pty: false }, (err, stream) => {
      if (err) return reject(err);
      let code = 0;
      stream.on('close', (c) => resolve(c ?? code)).on('exit', (c) => { code = c ?? 0; })
        .on('data', (d) => process.stdout.write(d)).stderr.on('data', (d) => process.stderr.write(d));
    });
  });
}
function put(conn, local, remote) {
  return new Promise((resolve, reject) => {
    conn.sftp((err, sftp) => {
      if (err) return reject(err);
      sftp.fastPut(local, remote, (e) => (e ? reject(e) : resolve(0)));
    });
  });
}
function putString(conn, contents, remote) {
  const tmp = path.join(os.tmpdir(), `deploy-${Date.now()}.tmp`);
  fs.writeFileSync(tmp, contents, 'utf8');
  return put(conn, tmp, remote).finally(() => fs.rmSync(tmp, { force: true }));
}

async function main() {
  console.log(`Deploying backend → ${USER}@${HOST}:${APP_DIR} (env-only=${ENV_ONLY})`);
  const envContents = buildServerEnv();
  let tarball = null;
  if (!ENV_ONLY) {
    console.log('Building backend tarball…');
    tarball = buildTarball();
    console.log(`  ${(fs.statSync(tarball).size / 1024).toFixed(0)} KB`);
  }

  const conn = await connect();
  try {
    await exec(conn, `mkdir -p ${APP_DIR} ${DATA_DIR}`);
    console.log('Uploading .env…');
    await putString(conn, envContents, `${APP_DIR}/.env`);

    if (!ENV_ONLY) {
      console.log('Uploading code…');
      await put(conn, tarball, `${APP_DIR}/deploy.tgz`);
      console.log('Extracting…');
      await exec(conn, `cd ${APP_DIR} && tar -xzf deploy.tgz --warning=no-unknown-keyword && rm -f deploy.tgz`);
      if (!SKIP_INSTALL) {
        console.log('Installing dependencies (npm install --omit=dev)…');
        const code = await exec(conn, `cd ${APP_DIR} && npm install --omit=dev --no-audit --no-fund 2>&1 | tail -5`);
        if (code !== 0) throw new Error(`npm install failed (exit ${code})`);
      }
    }

    console.log('Restarting service…');
    await exec(conn, `systemctl restart ${SERVICE} && sleep 4 && systemctl is-active ${SERVICE}`);
    console.log('Verifying HTTPS endpoint…');
    const code = await exec(conn, `curl -fsS -m 15 ${API_BASE}/api/config/mapbox && echo && echo VERIFY_OK`);
    if (code !== 0) {
      console.error('\nVerification failed. Recent logs:');
      await exec(conn, `tail -n 30 /var/log/${SERVICE}.log`);
      throw new Error('Post-deploy verification failed');
    }
    console.log('\n✅ Deploy complete — https://api.geosyntra.org is live.');
  } finally {
    conn.end();
    if (tarball) fs.rmSync(tarball, { force: true });
  }
}

main().catch((e) => { console.error('Deploy error:', e.message); process.exit(1); });
